sudo: false
language: java
jdk:
  - oraclejdk8
env:
  matrix:
    - GEOTOOLS_VERSION='13.4'   GEOSERVER_VERSION='2.7.4' ELASTICSEARCH_VERSION='1.4.4' ELASTICSEARCH_PROFILE_VERSION=1
    - GEOTOOLS_VERSION='13.4'   GEOSERVER_VERSION='2.7.4' ELASTICSEARCH_VERSION='1.5.2' ELASTICSEARCH_PROFILE_VERSION=1
    - GEOTOOLS_VERSION='13.4'   GEOSERVER_VERSION='2.7.4' ELASTICSEARCH_VERSION='1.7.3' ELASTICSEARCH_PROFILE_VERSION=1
    - GEOTOOLS_VERSION='13.4'   GEOSERVER_VERSION='2.7.4' ELASTICSEARCH_VERSION='2.1.1' ELASTICSEARCH_PROFILE_VERSION=2
    - GEOTOOLS_VERSION='14.1'   GEOSERVER_VERSION='2.8.1' ELASTICSEARCH_VERSION='1.4.4' ELASTICSEARCH_PROFILE_VERSION=1
    - GEOTOOLS_VERSION='14.1'   GEOSERVER_VERSION='2.8.1' ELASTICSEARCH_VERSION='1.5.2' ELASTICSEARCH_PROFILE_VERSION=1
    - GEOTOOLS_VERSION='14.1'   GEOSERVER_VERSION='2.8.1' ELASTICSEARCH_VERSION='1.7.3' ELASTICSEARCH_PROFILE_VERSION=1
    - GEOTOOLS_VERSION='14.1'   GEOSERVER_VERSION='2.8.1' ELASTICSEARCH_VERSION='2.1.1' ELASTICSEARCH_PROFILE_VERSION=2

cache:
  directories:
  - $HOME/.m2
install: "mvn -q install -DskipTests=true -Dgeotools.version=${GEOTOOLS_VERSION} -Dgeoserver.version=${GEOSERVER_VERSION} -Delasticsearch.version=${ELASTICSEARCH_VERSION} -Pelasticsearch${ELASTICSERCH_PROFILE_VERSION}"
script: "mvn -q verify -Dgeotools.version=${GEOTOOLS_VERSION} -Dgeoserver.version=${GEOSERVER_VERSION} -Delasticsearch.version=${ELASTICSEARCH_VERSION} -Pelasticsearch${ELASTICSERCH_PROFILE_VERSION}"
after_success:
  - mvn coveralls:report -Dgeotools.version=${GEOTOOLS_VERSION} -Dgeoserver.version=${GEOSERVER_VERSION} -Delasticsearch.version=${ELASTICSEARCH_VERSION} -Pelasticsearch${ELASTICSERCH_PROFILE_VERSION}"

