sudo: false
language: java
jdk:
- oraclejdk8
env:
  matrix:
  - GEOTOOLS_VERSION='15.3'   GEOSERVER_VERSION='2.9.3' ES1_VERSION='1.7.6' ES2_VERSION='2.3.5' ES_PROFILE_VERSION=1
  - GEOTOOLS_VERSION='16.0'   GEOSERVER_VERSION='2.10.0' ES1_VERSION='1.7.6' ES2_VERSION='2.3.5' ES_PROFILE_VERSION=1
  - GEOTOOLS_VERSION='15.3'   GEOSERVER_VERSION='2.9.3' ES1_VERSION='1.7.3' ES2_VERSION='2.3.5' ES_PROFILE_VERSION=2
  - GEOTOOLS_VERSION='15.3'   GEOSERVER_VERSION='2.9.3' ES1_VERSION='1.7.3' ES2_VERSION='2.4.2' ES_PROFILE_VERSION=2
  - GEOTOOLS_VERSION='16.0'   GEOSERVER_VERSION='2.10.0' ES1_VERSION='1.7.3' ES2_VERSION='2.3.5' ES_PROFILE_VERSION=2
  - GEOTOOLS_VERSION='16.0'   GEOSERVER_VERSION='2.10.0' ES1_VERSION='1.7.3' ES2_VERSION='2.4.2' ES_PROFILE_VERSION=2
cache:
  directories:
  - "$HOME/.m2"
install: "mvn install -DskipTests=true -Dgeotools.version=${GEOTOOLS_VERSION} -Dgeoserver.version=${GEOSERVER_VERSION} -Delasticsearch1.version=${ES1_VERSION} -Delasticsearch2.version=${ES2_VERSION} -Pelasticsearch${ES_PROFILE_VERSION}"
script: "mvn verify -Dgeotools.version=${GEOTOOLS_VERSION} -Dgeoserver.version=${GEOSERVER_VERSION} -Delasticsearch1.version=${ES1_VERSION} -Delasticsearch2.version=${ES2_VERSION} -Pelasticsearch${ES_PROFILE_VERSION}"
after_success:
- mvn coveralls:report -Dgeotools.version=${GEOTOOLS_VERSION} -Dgeoserver.version=${GEOSERVER_VERSION} -Delasticsearch1.version=${ES1_VERSION} -Delasticsearch2.version=${ES2_VERSION} -Pelasticsearch${ES_PROFILE_VERSION}
- mvn package assembly:assembly -P deploy,elasticsearch${ES_PROFILE_VERSION} -pl gs-web-elasticsearch -Dgeotools.version=${GEOTOOLS_VERSION} -Dgeoserver.version=${GEOSERVER_VERSION} -Delasticsearch1.version=${ES1_VERSION} -Delasticsearch2.version=${ES2_VERSION} -Pelasticsearch${ES_PROFILE_VERSION}
before_deploy:
  - if [ ${ES_PROFILE_VERSION} == "1" ];
    then export PLUGIN_FILE="$(ls gs-web-elasticsearch/target/elasticgeo*gs${GEOSERVER_VERSION}-es${ES1_VERSION}.zip)";
    else export PLUGIN_FILE="$(ls gs-web-elasticsearch/target/elasticgeo*gs${GEOSERVER_VERSION}-es${ES2_VERSION}.zip)";
    fi
  - echo "Deploying $PLUGIN_FILE to GitHub releases"
deploy:
  provider: releases
  api_key:
    secure: UiMZusRpTSbs3BQWZxououT1VPj8LzUN4UYH8H+PcPdEEZfx/lDNCxlaj1YG8eVCflJL1TItPdU8jIEU435weP4v3cnSyUjq/3Oc4ey9CK/iuphoqvkqfCgRxpVsj9wuZkJqLobi9+9JFLz6NziCnX9ME5WxRgMPlfRU2jot/GM=
  file_glob: true
  skip_cleanup: true
  file: "$PLUGIN_FILE"
  on:
    tags: true
